Testing Secret in production environment

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -43,6 +43,9 @@ jobs:
     if: github.event_name == 'push' && github.ref == 'refs/heads/main'
     runs-on: ubuntu-latest
 
+    environment:
+      name: production
+
     steps:
 
       - name: Setup Java
@@ -58,6 +61,15 @@ jobs:
 
       - name: Show downloaded JAR
         run: ls -lh
+
+      - name: Test environment secret
+        run: |
+          if [ -n "${{ secrets.TEST_SECRET }}" ]; then
+            echo "TEST_SECRET is configured"
+          else
+            echo "TEST_SECRET is missing"
+            exit 1
+          fi
 
       - name: Start application
         run: |
