Log Failed Smoke test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -57,10 +57,20 @@ jobs:
       - name: Start application
         run: |
           java -jar task-manager-0.0.1-SNAPSHOT.jar > application.log 2>&1 &
-          sleep 15
+          sleep 30
           echo "===== APPLICATION LOG ====="
           cat application.log
 
+
       - name: Smoke test
         run: |
-          curl --fail http://localhost:8080
+          for i in {1..30}; do
+            if curl --fail http://localhost:8080; then
+              echo "Application is healthy"
+              exit 0
+            fi
+            sleep 1
+          done
+          echo "Application failed to start"
+          cat application.log
+          exit 1
